TOP=../..

include $(TOP)/configure/CONFIG

# -------------------------------
# Build an Diamond Support Module
# -------------------------------

LIBRARY_IOC += DruckDPI515

# xxxRecord.dbd will be installed into <top>/dbd
DBD += DruckDPI515.dbd

# The following are compiled and added to the support library
DruckDPI515_SRCS += DruckDPI515.cpp

# ---------------------------------------------------

include $(TOP)/configure/RULES
